### ISSUE TITLE
14/3I — i18n — sprawdzić najmniejszy pozostały błąd poza zadaniami PK1

### ISSUE THREAD

**Issue by aslocka2026** [aleksanderem/crm_new#5120]
@claude

Wykonaj wyłącznie małą diagnostykę naszego wcześniejszego ciągu i18n / TypeScript.

Kontekst:
- nie dotykamy żadnych zadań ani zmian z planu PK1 Olka,
- nie analizuj migracji Convex → Supabase,
- nie naprawiaj niczego z auto-followupów Olka,
- interesują nas wyłącznie pozostałe błędy z naszego wcześniejszego ciągu i18n / TypeScript.

Zakres:
1. Uruchom aktualny typecheck.
2. Pomiń błędy wynikające z obszarów objętych PK1 / migracją Convex → Supabase.
3. Znajdź najmniejszy pojedynczy plik poza tym zakresem, który nadal ma błąd związany z:
   - t(),
   - TFunction,
   - typem unknown wynikającym z i18n,
   - bezpośrednim skutkiem wcześniejszych zmian i18n.
4. Niczego nie naprawiaj.

Nie:
- nie zmieniaj kodu,
- nie twórz PR,
- nie twórz follow-up issues,
- nie analizuj PK1,
- nie rozszerzaj zakresu na inne błędy TypeScript.

Na końcu podaj tylko:
1. dokładny plik,
2. dokładny błąd,
3. liczbę takich błędów w tym pliku,
4. najmniejszy możliwy zakres przyszłej poprawki.

Minimal diagnostic only.

**Comment by aleksanderem** [comment]
⏸️ **Poza bieżącym planem uruchomienia.** Zgłoszenie jest wyłącznie diagnostyką (bez zmian kodu) błędów TypeScript związanych z i18n spoza zakresu PK1 — autor wprost wyklucza jedynego kandydata (PK1 kol 2: Naprawić 35 błędów TypeScript), a żaden inny pakiet nie obejmuje diagnostyki błędów i18n/TFunction. Nie realizuje żadnego warunku uruchomieniowego planu.

Trafia do backlogu — wrócimy po starcie.

**Comment by aleksanderem** [comment]
🤖 I have a complete diagnostic picture. Let me provide the findings:

---

## Diagnostic Report — Issue #5120

### Full typecheck status

Running `tsc -p tsconfig.app.json` crashes the TypeScript 5.5.4 compiler before producing any output:

```
Error: Debug Failure. No error for last overload signature
  at chooseOverload → getSignatureApplicabilityError → resolveCallExpression
```

The crash is 100% caused by commit `7528f267` — replacing `Record<string, unknown>` with `typeof translation` in `src/i18next.d.ts`. Without that file in the compilation, the crash disappears. The crash is a known TypeScript compiler bug in overload resolution triggered by deeply-nested typed i18next resources combined with `t(x: string)` calls where `x` is dynamically typed.

### Smallest file with a concrete i18n TS error (non-crash)

**File**: `src/components/crm/date-range-picker.tsx`

**Error** (×2):

```
src/components/crm/date-range-picker.tsx(41,10): error TS2345:
  Argument of type '[string]' is not assignable to parameter of type
  '[key: TemplateStringsArray | "dateRange.today" | "dateRange.last7days" | ... 4224 more ...]'
  
src/components/crm/date-range-picker.tsx(78,18): error TS2345: (same)
```

**Root cause**: The `PRESETS` array at line 17 types `labelKey` as `string`:
```typescript
const PRESETS: { value: TimeRange; labelKey: string }[] = [...]
```
After the TypeResources augmentation, `t(preset.labelKey)` (line 78) and `t(activePreset.labelKey)` (line 41) both fail because `string` is not assignable to the strict key union from `typeof translation`.

**Error count in this file**: 2

**Minimal future fix scope**: Single change in `date-range-picker.tsx` — narrow `labelKey: string` to the literal union `"dateRange.today" | "dateRange.last7days" | "dateRange.last30days" | "dateRange.thisMonth" | "dateRange.last3months" | "dateRange.thisYear" | "dateRange.all"` (or use `Parameters<typeof t>[0] & string`). No other file needs to change for this specific error.

**Note on the crash**: The crash itself is separately triggered by `src/components/layout/app-footer.tsx` (same `t(x: string)` pattern) — this is the TypeScript compiler bug that prevents the full typecheck from outputting any errors. The crash and the date-range-picker errors are two separate manifestations of the same root cause: the TypeResources augmentation requires all `t()` call sites to use literal string keys, but several components use `labelKey: string` typed arrays.

---
_Reply with `@claude` and any additional info to continue._

**Comment by aleksanderem** [comment]
🙋 **Wymaga decyzji człowieka (groomer).** Raport workera uciął się w połowie zdania ("### Smallest file with a concrete") — znaleziono przyczynę crashu (i18next.d.ts, commit 7528f267), ale brakuje pozycji 3–4 z zakresu (liczba błędów w pliku, minimalny zakres poprawki). Czy ta częściowa diagnoza (crash kompilatora TS spowodowany typowaniem i18next) wystarczy do zamknięcia zgłoszenia i odłożenia reszty do backlogu, czy chcesz dokończyć pełny raport?

_Zgłoszenie jest czysto diagnostyczne (zero zmian kodu). Człowiek (@aleksanderem) już zdecydował: backlog, wrócimy po starcie. Worker zaczął raport i znalazł root cause (crash kompilatora przez i18next.d.ts), ale komentarz uciął się przed wymaganymi pozycjami 3 i 4 z pierwotnego zakresu. Nie można oznaczyć jako resolved — raport jest niekompletny. Nie ma co rozbijać (split) — to jednorazowa diagnostyka. Potrzebna decyzja człowieka: czy częściowy wynik wystarczy, czy dokończyć._

**Comment by aslocka2026** [comment]
Nie kontynuuj tej diagnostyki.

Częściowy wynik jest wystarczający.
Temat i18n / TypeScript odkładamy do backlogu i wrócimy do niego osobno.

Nie zmieniaj kodu i nie twórz follow-up issues.
